### ISSUE TITLE
Support for role-based access to payload?

### ISSUE THREAD

**Issue by nathanclevenger** [CrawlerCode/payload-authjs#6]
Is there support for role-based access where only some Auth.js users (like with a `role` of `admin`) have access to the Payload admin portal?

Following the same example in the docs, if the `users` collection is extended with a `role` field, can this be configured such that only `user?.roles?.includes("admin")` has access to the payload admin portal?  Or is this possibly be configuring a different collection for `users` and `admins`?  

Is this possible today or would it require a modification to this plugin?

**Comment by xfloor** [comment]
@nathanclevenger you can create infinite authentication collections (admins, customers, ...)  just by adding `auth: true` in the collection config.

Then, in the Payload Config, you define the slug of the collection that you want to be used to log in to the Admin dashboard: `{ admin: { user: "auth-enabled-collection-slug", ... } ... }`

> Is there support for role-based access where only some Auth.js users (like with a `role` of `admin`) have access to the Payload admin portal?
> 
> Following the same example in the docs, if the `users` collection is extended with a `role` field, can this be configured such that only `user?.roles?.includes("admin")` has access to the payload admin portal? Or is this possibly be configuring a different collection for `users` and `admins`?
> 
> Is this possible today or would it require a modification to this plugin?

**Comment by CrawlerCode** [comment]
Yes, exactly, @xfloor is right. you can create as many auth collections as you like.

You also have the option of restricting access to the admin portal. See the payload docs [here](https://payloadcms.com/docs/access-control/collections#admin).
Just create a collection called `users` and add an access controll check for admin. For example:
```typescript
const Users: CollectionConfig = {
  slug: "users",
  access: {
    admin: ({ req: { user } }) => {
      return user?.roles?.includes("admin") ?? false;
    },
  },
  fields: []
};
```

**Comment by nathanclevenger** [comment]
Thanks @xfloor and @CrawlerCode!  I knew that you could create multiple user collections, and handle access at the collection level, but I had missed the option to control access at the admin level ... which is exactly what we needed.  

Really appreciate it!
